### ISSUE TITLE
Nov 24 17:54:42 matrix_03 libvirtd: 2018-11-24 09:54:42.785+0000: 1809955: error : virNetSocketReadWire:1808 : End of file while reading data: Input/output error

### ISSUE THREAD

**Issue by sunnoy** [zhangjianweibj/prometheus-libvirt-exporter#10]
编译完成报错

Nov 24 17:54:42 matrix_03 libvirtd: 2018-11-24 09:54:42.785+0000: 1809955: error : virNetSocketReadWire:1808 : End of file while reading data: Input/output error

**Comment by zhangjianweibj** [comment]
go build编译错误??看着是运行错误，libvirt没启动吧？sudo service libvirt status ， sudo virsh list
