### ISSUE TITLE
Instance is shutoff after scraping

### ISSUE THREAD

**Issue by wat101** [zhangjianweibj/prometheus-libvirt-exporter#11]
When I ran ./prometheus-libvirt-exporter on a hypervisor, all instances were shutoff after scraping. Pls see below lines from /var/log/qemu/instance.log

2018-12-06T08:06:35.153855Z qemu-kvm: terminating on signal 15 from pid 118942 (/usr/sbin/libvirtd)
2018-12-06 08:06:35.409+0000: shutting down, reason=shutdown

OS, libvirt and qemu version on the hypervisor
# hostnamectl |egrep "OS|Kernel"
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.5:GA:server
            Kernel: Linux 3.10.0-862.6.3.el7.x86_64

# libvirtd -V
libvirtd (libvirt) 3.9.0

# /usr/libexec/qemu-kvm --version
QEMU emulator version 2.10.0(qemu-kvm-rhev-2.10.0-21.el7_5.3)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

**Comment by zhangjianweibj** [comment]
"signal 15" means send shutdown cmd to system.but libvirt-exporter only get merics from libvirt not send any action command to libvirt.maybe oom killed by system,you can find this issue throug system log.or scarpe intervel to low that cause libvirt protection mechanism shutdown vm.we test libvirt-exporter in centos and redhat system,but not occured this problem.

**Comment by wat101** [comment]
I also didn't think the issues was related to the exporter earlier, but I'm pretty sure it's the scraping somehow triggered the shutoff action after a few round tests.

I have just one 1x2 VM running on a hypervisor w/ 512G ram. I have not added the node as a target in Prometheous yet. As soon as I paste the metrics link (http://<hypervisor-ip:9000/metrics) in browser and hit enter, the vm state changed from running to shutoff immediately.

**Comment by zhangjianweibj** [comment]
it is a amazing thing.your can try telegraf plugin ,https://github.com/dahendel/telegraf/blob/master/plugins/inputs/libvirt/README.md.
telegraf has prometheus output plugin.i use this telegraf libvirt plugin,works well.your can try this plugin.and tell me is this plugin works well?very thanks.

**Comment by wat101** [comment]
Thanks for the suggestion. I tried again today with below option, and I don't see instances get shutoff now. Metrics can be scraped properly. Any clue why is this?

$ prometheus-libvirt-exporter **-libvirt.uri /var/run/libvirt/libvirt-sock-ro**

**Comment by zhangjianweibj** [comment]
yeah,libvirt-sock-ro only has read authority.it is a reliable way to get information from libvirt.

**Comment by lowang-bh** [comment]
for _, domain := range domains {
		err = CollectDomain(ch, l, &domain)
		l.DomainShutdown(domain)
		//domain.Free()
		if err != nil {
			log.Fatalf("failed to Collect domain: %v", err)
			return err
		}
	}

It is clearly that all domains will be shut down  from the code where DomainShutdown is called,.

**Comment by zhangjianweibj** [comment]
@lowang-bh ok,very thanks.i merged a dev branch that lead to the serious problem.

**Comment by zhangjianweibj** [comment]
fixed
