### ISSUE TITLE
libvirtSchema.Metadata.NovaInstance.Owner undefined 

### ISSUE THREAD

**Issue by wat101** [zhangjianweibj/prometheus-libvirt-exporter#13]
Got below error when I tried to build with the latest code today.

$ go build prometheus-libvirt-exporter.go
\# command-line-arguments
./prometheus-libvirt-exporter.go:149:49: libvirtSchema.Metadata.NovaInstance.Owner undefined (type libvirt_schema.NovaInstance has no field or method Owner)
./prometheus-libvirt-exporter.go:150:47: libvirtSchema.Metadata.NovaInstance.Owner undefined (type libvirt_schema.NovaInstance has no field or method Owner)
./prometheus-libvirt-exporter.go:152:52: libvirtSchema.Metadata.NovaInstance.Owner undefined (type libvirt_schema.NovaInstance has no field or method Owner)
./prometheus-libvirt-exporter.go:153:50: libvirtSchema.Metadata.NovaInstance.Owner undefined (type libvirt_schema.NovaInstance has no field or method Owner)

**Comment by zhangjianweibj** [comment]
is anything wrong with your project env?
![image](https://user-images.githubusercontent.com/18585129/58403612-bb28b380-8095-11e9-874c-0074ddf46aee.png)

Owner   filed exists in NovaInstance struct ,check this (https://github.com/zhangjianweibj/prometheus-libvirt-exporter/blob/master/libvirt_schema/schema.go) file.i hava cloned this project and run go build.
no any error.


![image](https://user-images.githubusercontent.com/18585129/58403746-017e1280-8096-11e9-800c-77eb0bbc31cd.png)

**Comment by wat101** [comment]
thanks for the quick response. I re-cloned the package under $GOPATH/src/github.com/zhangjianweibj/ directory, and then was able to build the exporter.

**Comment by zhangjianweibj** [comment]
yeah,go package manage is not equal to java and other language.sometimes it is very difficult to config project env.but since go 12 version,go supply module manage(go mod ) .it can help you reduce many project module configuration.

**Comment by wat101** [comment]
However, I do not see project name, project id or user user tags in the metrics...

**Comment by wat101** [comment]
Pls ignore above question, removed  -libvirt.uri /var/run/libvirt/libvirt-sock-ro from command line solved the issue.
