### ISSUE TITLE
libvirtd: End of file while reading data: Input/output error

### ISSUE THREAD

**Issue by defenestration** [zhangjianweibj/prometheus-libvirt-exporter#16]
The exporter seems to cause this error with libvirtd when it is scraped (so every 30 seconds or so)

`libvirtd[29503]: End of file while reading data: Input/output error`

I found related problem at https://access.redhat.com/solutions/2834501 

Which basically boils down to; 

```
Root Cause
Libvirt will log the above error message when only a 3way handshake followed by a close of the socket is executed against one of its ports.
```

Apparently not closing the port immediately would fix this but I am not sure how this could be implemented offhand.

**Comment by zhangjianweibj** [comment]
ok,thanks.can you copy the error message in this issue.we can analyze the  reason causing this problem.

**Comment by defenestration** [comment]
think #18 resolves this.
