### ISSUE TITLE
release file corrupted

### ISSUE THREAD

**Issue by fabricat** [zhangjianweibj/prometheus-libvirt-exporter#22]
The release downloaded by https://github.com/zhangjianweibj/prometheus-libvirt-exporter/releases/download/v1.1.0/prometheus-libvirt-exporter-1.1.0_linux_x86_64.tar.gz does not contain a valid binary.

I'd take great profit by having a compiled release (as expected after #19). E.g. I can install it on my hosts using Ansible (see this role https://github.com/entercloudsuite/ansible-prometheus-exporter).

Please, is it possible to re-release with a working binary?

**Comment by zhangjianweibj** [comment]
hi @fabricat ，we build exporter in ubuntu 16.04 env.and run in ubuntu 16.04,centos 6.not find any error.can you show us the wrong information?

**Comment by fabricat** [comment]
Hi, I confirm that I have no problems with building the binary from source.
The issue is in the tar.gz archive available on the [release page](https://github.com/zhangjianweibj/prometheus-libvirt-exporter/releases/tag/v1.1.0).
If you download and extract the archive, you will find only one file containing 1024 NULL bytes.
Should that contain a valid executable binary for "linux_x86_64"?

**Comment by zhangjianweibj** [comment]
![image](https://user-images.githubusercontent.com/18585129/90003970-75223480-dcc7-11ea-8e21-1986336e8328.png)
hi,
i hava rebuild the exporter in our linux_x86-64 env.you can try again

**Comment by fabricat** [comment]
Yes, I can confirm that the archive now contains a valid binary.
Thank you.
