### ISSUE TITLE
The memory usage capture incorrect

### ISSUE THREAD

**Issue by ucontacti** [zhangjianweibj/prometheus-libvirt-exporter#23]
I am trying to get the memory usage by "libvirt_domain_info_memory_usage_bytes" metric. But the value is constant.
I guess you are returning the actual memory from libvirt API which I can see using virsh dommemstat.

**Comment by zhangjianweibj** [comment]
metrics libvirt_domain_info_memory_usage_bytes is a gauge type value.
ch <- prometheus.MustNewConstMetric(
		libvirtDomainInfoMemoryDesc,
		prometheus.GaugeValue,
		float64(rmemory)*1024,

**Comment by ucontacti** [comment]
Thanks for your answer. I don't think the type value of this metric is my concern. Sure it is a gauge value type, cause it is supposed to represent memory usage in bytes and that is what gauge value type is for. 
What I am concerned about is that this metric does not change at all. And I do not see any other metric to monitor the memory usage of a specific domain in this exporter.

**Comment by alibo** [comment]
@zhangjianweibj 

`DomainGetInfo(*domain)` method from `go-libvirt` package (which is used [here](https://github.com/zhangjianweibj/prometheus-libvirt-exporter/blob/master/prometheus-libvirt-exporter.go)) returns values of `<maxMemory>` and `<currentMemory>` and they only show the allocated memory.

> 
> **maxMemory**
> 
> The run time maximum memory allocation of the guest. The initial memory specified by either the <memory> element or the NUMA cell size configuration can be increased by hot-plugging of memory to the limit specified by this element. The unit attribute behaves the same as for <memory>. The slots attribute specifies the number of slots available for adding memory to the guest. The bounds are hypervisor specific. Note that due to alignment of the memory chunks added via memory hotplug the full size allocation specified by this element may be impossible to achieve. Since 1.2.14 supported by the QEMU driver.
>
> **currentMemory**
> 
> The actual allocation of memory for the guest. This value can be less than the maximum allocation, to allow for ballooning up the guests memory on the fly. If this is omitted, it defaults to the same value as the memory element. The unit attribute behaves the same as for memory.
> https://libvirt.org/formatdomain.html#memory-allocation

If memory is not over-committed, both values are the same.

To get the memory usage of a VM, you need to use `DomainMemoryStats()` method:
https://github.com/digitalocean/go-libvirt/blob/e2a69bcd5bd163f61a7e222cf915101e7e11b1c6/remote_protocol.gen.go#L8950 

it returns an array of these fields:
https://github.com/digitalocean/go-libvirt/blob/e2a69bcd5bd163f61a7e222cf915101e7e11b1c6/const.gen.go#L783-L799

**Comment by alibo** [comment]
You can also check these exporters for more information (however they're using `libvirt/libvirt-go` package)

- https://github.com/fitbeard/libvirt_exporter
- https://github.com/vexxhost/libvirtd_exporter/commit/4c96215c79138cba4b1840b6f0f239bd1ec83cb5

**Comment by zhangjianweibj** [comment]
thanks for your proposal, https://github.com/zhangjianweibj/prometheus-libvirt-exporter/pull/24  fixed this issue.
