### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by IAOTW** [zhangjianweibj/prometheus-libvirt-exporter#25]
这个是不是只支持华为云呢，跑起来后发现是这样的openstack_ceilometer_metric_scrape_duration_ns{metric="cpu"} 2.2590131e+09  不知道怎么加上标签，这个能监控到每台虚拟机吗

**Comment by zhangjianweibj** [comment]
这个是在标准的openstack原生上开发的功能，不针对某些云厂商。采集器放在计算节点上即可，可监控到宿主机上运行的虚机情况。可参考下prometheus的使用

**Comment by IAOTW** [comment]
我运行后有报错，而且没有instance-id这些额外的label信息，exporter我是在自己的电脑上启动的，我这边openstack上有10多台机器，但没有都显示出来，我没找到原因
![image](https://user-images.githubusercontent.com/53284613/115811820-ff0fc900-a422-11eb-8975-e7cb3cc4dbd7.png)
![image](https://user-images.githubusercontent.com/53284613/115811842-0afb8b00-a423-11eb-8a29-13d3996e3c8b.png)

**Comment by zhangjianweibj** [comment]
你openstack环境是什么样的？看着指标不是compute节点

**Comment by IAOTW** [comment]
openstack是个all in one的机器，刚刚在自己电脑上运行后报错
failed to dial libvirt: dial unix /var/run/libvirt/libvirt-sock: connect: A socket operation encountered a dead network.
exporter必须运行在openstack的节点吗,没有发现填写keystone配置的地方
