### ISSUE TITLE
能否扩展磁盘监控查询

### ISSUE THREAD

**Issue by youflint** [zhangjianweibj/prometheus-libvirt-exporter#5]
有没有拓展查询domain上磁盘占用空间、未占用空间的方法

**Comment by zhangjianweibj** [comment]
安装ceilometer 的agent到被监控对象，可以取出非常非常详细的信息，包括你需要的。然后扩展个exporter从mq中取出监控数据。

**Comment by Jerryhax** [comment]
运行后控制台结果：
2018/06/22 17:52:45 failed to connect: 需要验证

Process finished with exit code 1
这是什么情况？

**Comment by zhangjianweibj** [comment]
@Jerryhax 详细错误信息贴出来看看。启动需要指定libvirt-sock文件。 -h 看看命令说明

**Comment by Jerryhax** [comment]
怎么看更详细的错误信息？我是在vm下的Fedora里的goland里运行的，所有依赖都导入了，只有控制台出了这个啊

**Comment by zhangjianweibj** [comment]
@Jerryhax virsh -c qemu:///system list   看看你的LibVirtd启动了没

**Comment by Jerryhax** [comment]
[root@server1 ~]# systemctl libvirtd rstart
Unknown operation 'libvirtd'.

**Comment by zhangjianweibj** [comment]
@Jerryhax 我去。你这cmd用的。。。。。。估计是LibVirtd没起成功，或者启动成功了但权限不是root。你自己好好瞧瞧吧。

![image](https://user-images.githubusercontent.com/18585129/41828057-874c547e-7865-11e8-9c5c-589688d0d7b1.png)

**Comment by Jerryhax** [comment]
![image](https://user-images.githubusercontent.com/16162773/41828715-6333d554-7869-11e8-8696-8fb74a936dbe.png)
