### ISSUE TITLE
libvirt_domain_info_memory_usage_bytes有问题？

### ISSUE THREAD

**Issue by Jerryhax** [zhangjianweibj/prometheus-libvirt-exporter#6]
我把prometheus-libvirt-exporter运行起来了，数据也采集到了，用prometheus查看发现：
libvirt_domain_info_memory_usage_bytes和libvirt_domain_info_maximum_memory_bytes这两个测量数据始终一样
![image](https://user-images.githubusercontent.com/16162773/41840802-3f804432-7899-11e8-8b77-d4a0ef05e840.png)

**Comment by zhangjianweibj** [comment]
libvirt采集的方式，数据有偏差并且好多是不准确的。LibVirt仅仅能查询到给虚机分配的内存规格，但是看不到真实的使用情况。这个你可以查看下LibVirt的说明文档。如果你需要非常精确的数据，建议使用Telemetry。或者仅仅安装Telemetry采集端，从MQ取出监控数据存储到Prometheus。

**Comment by Jerryhax** [comment]
不好意思，我不是很了解，你说的是哪个Telemetry，能给个链接不？

**Comment by Jerryhax** [comment]
我是想监控一下服务器上每个虚拟机的使用情况CPU，memeory,Disk IO,Networt IO 这些。内存和已用内存一样大不合理啊，还有别的方法么？

**Comment by zhangjianweibj** [comment]
telemetry,openstack 自己的监控告警组件。https://docs.openstack.org/mitaka/install-guide-rdo/common/get_started_telemetry.html

**Comment by zhangjianweibj** [comment]
还有个方法，通过自动化或是修改镜像，在虚机里面添加telegraf，telegraf可以将监控数据直接发送到Prometheus，这个也是非常非常准确的。

**Comment by Jerryhax** [comment]
谢谢啊，环境不允许修改镜像，OpenStack 的telemetry服务能单独安装使用么？我这不是OpenStack环境

**Comment by zhangjianweibj** [comment]
依赖openstack，Telemetry本身就是openstack生态中的一个组件。直接调用nova，cinder等接口获取监控数据。要是不能修改镜像可以考虑写个agent或通过任务方式将telegraf下发到待监控虚机中。LibVirt监控一直存在不准确的问题，估计这个问题它是解决不了了。
